version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: bike_project
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: db
      OPENROUTESERVICE_API_KEY: YOUR_OPENROUTESERVICE_API_KEY
    depends_on:
      - db

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      DATABASE_NAME: bike_project
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: db
      OPENROUTESERVICE_API_KEY: YOUR_OPENROUTESERVICE_API_KEY
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bike_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
