# Use a base image with Python installed
FROM python:10

# Set the working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY app/ .

# Expose the ports the apps run on
EXPOSE 8000 8501

# Command to run both applications
CMD ["sh", "-c", "python api.py & streamlit run streamlit_app.py"]

