version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:




